services:
  auth-service:
    build: 
      context: ./services/auth_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - user-profile-service
      - kafka
    container_name: campushub_auth

  user-profile-service:
    build:
      context: ./services/user_profile_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./services/user_profile_service/.env.docker
    depends_on:
      - postgres
    container_name: campushub_user_profile

  api-gateway:
    build:
      context: ./services/api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./services/api_gateway/.env.docker
    environment:
      - NODE_ENV=docker
    depends_on:
      - auth-service
      - user-profile-service
    container_name: campushub_api_gateway

  events-service:
    build:
      context: ./services/events_service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./services/events_service/.env.docker
    depends_on:
      - postgres
      - api-gateway
    container_name: campushub_events
  
  logging-service:
    build:
      context: ./services/logging_service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    env_file:
      - ./services/logging_service/.env.docker
    depends_on:
      - kafka
      - mongodb
    container_name: campushub_logging_service

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    container_name: kafka

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    container_name: elasticsearch

  mongodb:
    image: mongo:latest
    container_name: campushub_mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_DATABASE=${MONGODB_DB}
  
  postgres:
    image: postgres:17
    container_name: campushub_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  mongodb_data:


