services:
  auth-service:
    build: 
      context: ./services/auth_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - user-profile-service
    container_name: campushub_auth


  user-profile-service:
    build:
      context: ./services/user_profile_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./services/user_profile_service/.env.docker
    depends_on:
      - postgres
    container_name: campushub_user_profile

  api-gateway:
    build:
      context: ./services/api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./services/api_gateway/.env.docker
    environment:
      - NODE_ENV=docker
    depends_on:
      - auth-service
      - user-profile-service
    container_name: campushub_api_gateway


  events-service:
    build:
      context: ./services/events_service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./services/events_service/.env.docker
    depends_on:
      - postgres
      - api-gateway
    container_name: campushub_events
  
  
  postgres:
    image: postgres:17
    container_name: campushub_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


