services:
  auth_service:
    build: 
      context: ./services/auth_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    container_name: campushub_auth


  user_profile_service:
    build:
      context: ./services/user_profile_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./services/user_profile_service/.env.docker
    depends_on:
      - postgres
    container_name: campushub_user_profile
  
  
  postgres:
    image: postgres:17
    container_name: campushub_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


