name: Auth Service CI/CD

on:
  push:
    paths:
      - 'services/auth_service/**'
      - '.github/workflows/auth.yml'
  pull_request:
    paths:
      - 'services/auth_service/**'
  
  workflow_dispatch:
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Test with Gradle
        working-directory: services/auth_service
        run: ./gradlew build --no-daemon

  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Server / Cloud
        run: |
          echo "Deploying auth_service..."
          # actual deployments will come here!


