name: User Profile Service CI/CD

on:
    push:
        paths:
            - 'services/user_profile_service/**'
            - '.github/workflows/user_profile.yml'
    pull_request:
        paths:
            - 'services/user_profile_service/**'
    
    workflow_dispatch:

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies
              working-directory: services/user_profile_service
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              working-directory: services/user_profile_service
              run: echo "No tests to run"
              # run: |
                # pytest

    
    deploy:
        needs: build-test
        if: github.ref == 'refs/heads/main' && success()
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy User Profile Service
              run: |
                echo "Deploying user profile service"
                # actual deployments will come here!


